# Build stage
FROM node:14.17.6-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:1.21.3-alpine
COPY --from=build /app/dist/FormationHaring /usr/share/nginx/html
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]